web:
  upload-path: /usr/local/app/inkjetpic
spring:
  datasource:
      url: jdbc:mysql://47.104.111.241:3306/inkjet?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        initial-size: 3
        min-idle: 3
        max-active: 50
        max-wait: 60000
        validation-query: select 'x'
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        filter:
          commons-log:
            connection-logger-name: stat,wall,log4j

  jpa:
    # 配置 DBMS 类型
    database: MYSQL
    # 配置是否将执行的 SQL 输出到日志
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          # 配置开启自动更新表结构
          auto: update
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  profiles:
    active: dev
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}

server:
  port: 80
  context-path: /inkjet
  servlet-path: /
